"""
Data models for the two-agent visual translator pipeline.

This module defines all Pydantic models used for type safety and validation
across the visual translation workflow:
- Agent 1 (Screenwriter) outputs: Storyline with StoryScene objects
- Agent 2 (Editor) outputs: Storyboard with Scene and VisualQuery objects
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# --- Video Summary Models ---

class VideoSummary(BaseModel):
    """
    Represents available footage from video analysis (e.g., qwen_analysis_sequence.json).
    Used as context for both agents to understand what footage is available.
    """
    video: str = Field(description="Path to video file")
    num_frames: int = Field(description="Number of frames analyzed in this video")
    description: str = Field(description="AI-generated description of video content")


# --- Agent 1 Output Models: Storyline ---

class StoryScene(BaseModel):
    """
    A single scene in the narrative structure, without visual queries yet.
    Output by Agent 1 (Screenwriter), consumed by Agent 2 (Editor).
    """
    narrative_id: str = Field(
        description="A short, unique slug summarizing this scene (e.g., 'mountain_drive_start', 'campfire_night')"
    )
    description: str = Field(
        description=(
            "Detailed cinematographic description of what should be shown in this scene. "
            "Include framing (wide shot, close-up, aerial), subject, setting, lighting, mood. "
            "Be specific about visual elements that can be matched to footage."
        )
    )
    rationale: str = Field(
        description="Why this scene fits the story and how it leverages available footage"
    )
    estimated_duration: int = Field(
        description="Estimated duration of this scene in seconds based on narrative pace",
        default=10
    )


class Storyline(BaseModel):
    """
    Complete narrative structure created by Agent 1 (Screenwriter).
    Contains ordered scenes that tell the story without specific CLIP queries yet.
    """
    scenes: List[StoryScene] = Field(
        description="Chronologically ordered scenes that tell the story"
    )
    overall_theme: Optional[str] = Field(
        description="Overall narrative theme/arc (optional)",
        default=None
    )


# --- Agent 2 Output Models: Storyboard ---

class VisualQuery(BaseModel):
    """
    A single CLIP-optimized search query for finding matching frames.
    Generated by Agent 2 (Editor) based on the storyline.
    """
    query_text: str = Field(
        description=(
            "A highly descriptive, concrete visual search query optimized for CLIP. "
            "MUST start with a framing keyword (e.g., 'A cinematic wide shot of...', 'A close-up photo of...'). "
            "MUST include the global context (location/time) and describe physical objects/colors. "
            "No abstract emotions. Maximum specificity for cosine similarity matching."
        )
    )
    weight: float = Field(
        description="Relevance score. Use 1.0 for direct visual matches, 0.8 for thematic matches.",
        default=1.0
    )
    reasoning: Optional[str] = Field(
        description="Internal note on why this query was chosen (not used in search, for debugging)",
        default=None
    )


class Scene(BaseModel):
    """
    Complete scene with visual queries - output of Agent 2 (Editor).
    This format is compatible with timeline_generator.py for frame matching.
    """
    narrative_id: str = Field(
        description="Must match the narrative_id from the input Storyline"
    )
    description: str = Field(
        description="Cinematographic description (copied from StoryScene for reference)"
    )
    rationale: str = Field(
        description="Reasoning for this scene (copied from StoryScene for reference)"
    )
    visual_queries: List[VisualQuery] = Field(
        description="3-5 distinct CLIP queries capturing different angles/aspects of this scene"
    )
    estimated_duration: int = Field(
        description="Estimated duration in seconds (copied from StoryScene)"
    )


class Storyboard(BaseModel):
    """
    Final output of the two-agent pipeline - complete storyboard with visual queries.
    This format is directly compatible with timeline_generator.py for frame matching.
    """
    scenes: List[Scene] = Field(
        description="Ordered scenes with CLIP-optimized visual queries"
    )
